language: node_js

node_js: stable

sudo: required

addons:
  chrome: stable

os:
  - linux

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: OR4o1qoSUfkWIRBeQJbjOQHitL5EHjhY9TQyvpdDWvP4KTch5raQ+d1QKv5nTdnXpUyC6jr6AjaBTkl7piRkmned6sS58w9LsPkOvhRc880+6W3pQr+fQSYnW+jrAKA5p3r7F99EcgtUpqrga+MXF0MlJX+1YkzoPF7JcMIk6VzWKyPBeTsFdjIwjJxtRoxT8DpS76HtnSR7eSkHjXwvQvvJKdFENyQQ1hjaVOLFgvFYKokwlqJVqGBpWTV5CmlUEVCQYlDKPWyjDsYobhVfeiGxGIgyfmJB7wGDRrMuY7Gpi1WDgihpeDg5mXHWyusTPvjPXo3fQxqHDBd9NAXYet8yyiUDOFZBzsDCmJFmto6A3ehBzbwaRh16J8RdeZXjzO2Drz5Ah6pZ7Hmu5LokeTFi8DybZGhGNc368/la2kecbqGL7UgmEkDPIX61FhOkFbdgikCezGHRG3f5qXhE4fTZ8eXO2Sw7GBHGsCq4+IEJG/QNdJd2K4L+XvG/D/CwhcEv+MhFPCSPd4Pl9i734XI5B5o3tLbaNkil/NUvJSLYVCqMEt9zr3vU4oK9MkatG2Vp0zz80z4arkAipMpHF7rrQqbLNaaOT/MaXr5Qk5WHDJ7pLEt6ZalHasgVoFqOFUR4yotXAm8ZV5EoUuGR6n+TTsElUy4medta8HC+DRY=
  app: intense-beach-95674
  on:
    repo: senthilkumar04/ysytweb
  run:
    - npm run build.prod
    - npm run serve.prod
